org.gradle.jvmargs=-Xmx768m -XX:MaxMetaspaceSize=256m
org.gradle.java.home=C:/Users/Sivasakthivel/.gradle/jdks/eclipse_adoptium-17-amd64-windows.2
org.gradle.workers.max=1
org.gradle.daemon=false
android.useAndroidX=true
android.overrideVersionCheck=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
